### ISSUE TITLE
group name 

### ISSUE THREAD

**Issue by Axio01** [taimaishuze/sootsplash.html#6]
#Protocol
Assante-dotsale
Othman- Othman4
Mohamed-Quraish313
Adam-Axio01
Johnny-Johnny174

**Comment by taimaishuze** [comment]
I added team name to all the .html and added your team member names.  Please make sure to read [README.md](https://github.com/taimaishuze/sootsplash.html/blob/master/README.md) to understand how to make changes.  Thank you
