### ISSUE TITLE
Linux star info

### ISSUE THREAD

**Issue by A2795** [taimaishuze/sootsplash.html#7]
Mussie Asrat
A2795
Linux star
https://github.com/kml74123/Web-Server-Team

**Comment by taimaishuze** [comment]
Please read the [README.md](https://github.com/taimaishuze/sootsplash.html/blob/master/README.md) to understand what is required.  Please try to customize your web page before we commit your request.  What you submit is pretty much what you're going to see on your web page.  Thank you.

**Comment by dyang32** [comment]
I've added your info into the home page but still need your team members info
